sudo: true
language: ruby
rvm:
  - 2.4.3
addons:
  apt:
    packages:
    - libgdal1h
    - libgdal-dev
    - gdal-bin
    - libcairo2-dev
    - libpango1.0-dev
before_install:
 - git clone https://github.com/propublica/simple-tiles.git
 - cd simple-tiles
 - ./configure && make
 - sudo make install
 - cd ..
 - gem install bundler -v 1.16.1
before_script:
  - gdalinfo --version
